# Generated by Django 5.0.7 on 2024-11-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="feedingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("data", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LightData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ON", "On"), ("OFF", "Off")],
                        default="OFF",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("workingTime", models.TimeField(default="00:00")),
                (
                    "desc",
                    models.CharField(
                        choices=[
                            ("Feeding ON", "Feeding"),
                            ("Light ON", "Lighton"),
                            ("Light OFF", "Lightoff"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "freq",
                    models.CharField(
                        choices=[("Today", "Today"), ("Everyday", "Everyday")],
                        default="Today",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Success", "Success")],
                        default="Pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="sensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("temp", models.FloatField(default=0)),
                ("ph", models.FloatField(default=0)),
                ("tds", models.FloatField(default=0)),
                ("waterLv", models.FloatField(default=0)),
                (
                    "eval",
                    models.CharField(
                        choices=[
                            ("Green", "Green"),
                            ("Orange", "Orange"),
                            ("Red", "Red"),
                        ],
                        default="Green",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="userToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=1000)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
