# Generated by Django 5.1.3 on 2024-11-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="desc",
            field=models.CharField(
                choices=[
                    ("Automatic Feed ON", "Feeding"),
                    ("Automatic Light ON", "Lighton"),
                    ("automatic Light OFF", "Lightoff"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
