# Generated by Django 5.1.3 on 2024-11-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_alter_schedule_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="lightdata",
            name="color",
            field=models.CharField(default="rgb(245, 255, 197)", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="desc",
            field=models.CharField(
                choices=[
                    ("Automatic Feed ON", "Feeding"),
                    ("Automatic Light ON", "Lighton"),
                    ("Automatic Light OFF", "Lightoff"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
