# Generated by Django 5.1.3 on 2024-11-13 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_lightdata_color_alter_schedule_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="workingDate",
            field=models.DateField(default=datetime.date(2024, 11, 13)),
        ),
    ]
