# Generated by Django 5.1.3 on 2024-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_schedule_workingdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="workingDate",
            field=models.DateField(),
        ),
    ]
