# Generated by Django 5.1.3 on 2024-12-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_schedule_workingdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="userPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minGrnTemp", models.FloatField(default=22.0)),
                ("maxGrnTemp", models.FloatField(default=28.0)),
                ("minOrgTemp", models.FloatField(default=19.0)),
                ("maxOrgTemp", models.FloatField(default=39.0)),
                ("minGrnPh", models.FloatField(default=7.0)),
                ("maxGrnPh", models.FloatField(default=8.0)),
                ("minOrgPh", models.FloatField(default=5.5)),
                ("maxOrgPh", models.FloatField(default=9.0)),
                ("minGrnTds", models.FloatField(default=250.0)),
                ("maxGrnTds", models.FloatField(default=400.0)),
                ("minOrgTds", models.FloatField(default=200.0)),
                ("maxOrgTds", models.FloatField(default=600.0)),
                ("grnWaterLv", models.FloatField(default=90)),
                ("orgWaterLv", models.FloatField(default=70)),
            ],
        ),
    ]
