# Generated by Django 5.1.3 on 2024-12-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_alter_sensordata_eval"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="tankHeight",
            field=models.FloatField(default=24),
        ),
    ]
